version: 2.1
orbs:
  node: circleci/node@5.0.1
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - aws-cli/setup
      - node/install
      - eb/setup
      - run:
          name: Front-end install
          command: |
            npm run frontend:install
      - run:
          name: Front-end Build
          command: |
            npm run frontend:build
      - run:
          name: Front-end Deploy
          command: |
            cd udagram/udagram-frontend
            aws s3 cp --recursive --acl public-read ./www s3://udagram-ui-bck/
      - run:
          name: Back-end Install
          command: |
            npm run api:install
      - run:
          name: Back-end Build
          command: |
            npm run api:build
      - run:
          name: Back-end Deploy
          command: |
            npm run api:deploy
workflows:
  build-deploy:
    jobs:
      - build:
        filters:
          branches:
            only: 
              - main